### ISSUE TITLE
Define list of maintainers for ReleaseManagement

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#1]
**Problem description**

We need volunteers who are commited to actively contribute to the Release Management of CAMARA across its sub projects.

"Maintainers are first and foremost contributors that have shown they are committed to the long-term success of a Sub Project", in this case of the Working Group "Release Management"

**Expected action**

- [x] Call for maintainers on mailing list release@lists.camaraproject.org (@hdamker)
- [ ] Collect commitments within this issue (all volunteers)
- [ ] Create PR with initial maintainers and ask TSC co-chairs for approval (@hdamker)

**Additional context**

Maintainers within this working group should be already active contributers in at least one CAMARA sub project.

**Comment by jlurien** [comment]
Hi @hdamker, I can contribute to this track as maintainer on behalf of TEF

**Comment by hdamker** [comment]
We still need one or two more maintainers/codeowner.
@wrathwolf could you address this within the next weekly meeting?

**Comment by wrathwolf** [comment]
Yes, we planned to address this yesterday at the Release Meeting, but we had to delay the meeting due to unforeseen circumstances.  I'm hoping that we can complete the training next week and seek some volunteers to be the Release Managers.  We are hoping to have at least 2.

**Comment by hdamker** [comment]
Closing ... next update if we have additional Release Managers
