### ISSUE TITLE
ICM r0.2.1 patch release review 

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#100]
**Release PR or issue to review**

https://github.com/camaraproject/IdentityAndConsentManagement/pull/202

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by tanjadegroot** [comment]
> @tanjadegroot would you be able to take that?

now yes :-) I reviewed and am OK with proposed PR that includes the review comments resolution.

**Comment by hdamker** [comment]
Approved the release PR, waiting for merge and release creation.

**Comment by hdamker** [comment]
Release is created. Meta-release page update with the new release tag, but kept the date of the M2 release (as the patch has not impact on the APIs, and the actual M2 release was done in August).

**Comment by hdamker** [comment]
@tanjadegroot would check the updated meta-release information and then close the issue?

**Comment by tanjadegroot** [comment]
The release tag 0.4.1 is not visible in the repo as the latest version. Should that not be the case ?
The Fall24 meta-release page on the wiki is thus also not updated.

Should we add 3 lines for "patch", "patch date" and "API impacts" in the table ?
"API impacts" would have values value: rx.y(.z): yes/no ?

**Comment by tanjadegroot** [comment]
Fall24 page is updated - so this issue can be closed. Closed as completed
