### ISSUE TITLE
DeviceIdentifier r1.1 (v0.2.0-alpha.1) release review

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#105]
**Release PR or issue to review**

- https://github.com/camaraproject/DeviceIdentifier/pull/85

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by eric-murray** [comment]
Proposed API version is 0.2.0-alpha.1. Device Identifier already has a 0.1.0 initial release.

**Comment by hdamker** [comment]
Updated the [release tracker](https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/23364462/device-identifier+0.2.0), issue can be closed.

cc: @eric-murray @tanjadegroot
