### ISSUE TITLE
DeviceStatus r1.3 patch release review

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#109]
**Release PR or issue to review**

- https://github.com/camaraproject/DeviceStatus/pull/216

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)
- [x] **PR on https://github.com/camaraproject/.github/blob/main/profile/README.md created** (by Release Management) and merged (by CAMARA admin)

**Additional comments**

**Comment by hdamker** [comment]
Created https://github.com/camaraproject/.github/pull/6 to address the last checkbox. Please review @tanjadegroot.

**Comment by tanjadegroot** [comment]
Review closed as completed
