### ISSUE TITLE
How to manage version for a API family release

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/ReleaseManagement#12]
**Problem description**
In the context of the Device Location API family we have several API (Yaml). One API for checking location, another for retrieving location and a third soon to be delivered for geofencing.
We wanted to manage release management at the family level as we have to provide consistency between the family.

Using numerical version for the family seems to us **not** a great idea as it will bring confusion - indeed, the Family in v0.2 will cover this API in v0.3, the other API in v0.2 and the third API in v0.1. Confusing right?

Perhaps have a name for a family version should be better but as this issue will come in several project we need to have a global common naming. Could the name of the family and then a release name using a word following alphabetical like Device Location family - Release Avocado, Device Location family - Release Banana, etc...

**Expected action**
Have a common agreement on API family release management

**Additional context**
Need to discuss if we manage this family stuff for one api family. I do not have clear idea on this as consistency is always good but not sure of the value of the family release in this case.

**Comment by tanjadegroot** [comment]
The release management process decouples the release numbering from API versioning. A release is done at the level of a repository. If there are several APIs in a repository, it can only be release if all of the APIs have at lease an initial API version (no WIP).
The related discussion on changing the notion API family to become a working group with associated API repositories which can be release separately (above issue #7) is moved to the backlog of the Governance group as  https://github.com/camaraproject/Governance/issues/135

**Comment by tanjadegroot** [comment]
Closed with the API Release Process (see above comment) and per https://wiki.camaraproject.org/display/CAM/2024-05-14+Release+WG+Minutes
