### ISSUE TITLE
Patch release r1.3 of CarrierBillingCheckout - to be shown in Fall24 release

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#124]
**Problem description**

CarrierBillingCheckout has done a path release in https://github.com/camaraproject/CarrierBillingCheckOut/pull/193 without involvement of the Release Management team. The release itself looks good to me.

The team has created new release trackers for the patch versions of the API: 
* https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/45973559/carrier-billing+v0.3.1 and 
* https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/46006353/carrier-billing-refund+v0.1.1.
This approach makes sense, as it avoids to overwrite the information within version published originally within the meta-release. We should think about to define as the general approach: every public release should have its own release tracker.

Two remaining issues:
* The patch release r1.3 does not show up on https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14549015/Meta-release+Fall24 - unclear why the new release tracker are not shown
* https://github.com/camaraproject/.github/blob/main/profile/README.md is not updated for CarrierBillingCheckout APIs

**Expected action**

* https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14549015/Meta-release+Fall24 does reflects the right (latest) patch release of CarrierBillingCheckout for the two APIs
* https://github.com/camaraproject/.github/blob/main/profile/README.md updated

**Additional context**

**Comment by hdamker** [comment]
> **Expected action**
> 
> * https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14549015/Meta-release+Fall24 does reflects the right (latest) patch release of CarrierBillingCheckout for the two APIs
>
I tried again to understand why the two release tracker for carrier-billing v0.3.1 and carrier-billing-refund v0.1.1 are not showing up within the table of the meta-release Fall24. To my understanding uses the table for filtering the two labels 
And within a [filtered view on these labels](https://lf-camaraproject.atlassian.net/wiki/label/CAM/camara-api-release-tracker+camara-fall24) the two release trackers are showing up, but still not on the Fall24 meta-release page.



> * https://github.com/camaraproject/.github/blob/main/profile/README.md updated
> 
Will get fixed by https://github.com/camaraproject/.github/pull/7 ... needs one approval before merge @tanjadegroot

**Comment by hdamker** [comment]
> I tried again to understand why the two release tracker for carrier-billing v0.3.1 and carrier-billing-refund v0.1.1 are not showing up within the table of the meta-release Fall24. To my understanding uses the table for filtering the two labels
> And within a [filtered view on these labels](https://lf-camaraproject.atlassian.net/wiki/label/CAM/camara-api-release-tracker+camara-fall24) the two release trackers are showing up, but still not on the Fall24 meta-release page.

Found it finally: the new release tracker have there tables not in the "page properties macro" of Confluence, but in simple tables. Hence the "page properties report" macro can not collect the content from these release trackers.

I propose to integrate the information of the additional release trackers into the original ones from the Fall24 release, as other patch releases have done as well. 

cc: @tanjadegroot

**Comment by tanjadegroot** [comment]
I calso found and corrected the bug which was indeed that the release tracker was missing the page properties macro.

To avoid such issues, I would highly recommend that we document the patches on the existing release tracker.

I propose to add guiliine that the patch shall

- update the release tracker page title to reflect the patch version 
- update the API version field
- NOT update the Target version field

**Comment by hdamker** [comment]
@tanjadegroot thanks for updating the release trackers for CarrierBilling accordingly. With that the issue can be closed.
