### ISSUE TITLE
How to handle ReleaseTracker for Patch Releases

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#125]
**Problem description**

In the context of #124 the question came up, how to handle the ReleaseTracker for patch releases (which are updating an API Repository release which is part of a meta-release).

Currently two different approaches are in use:

A) Update the original release tracker used within the meta-release

* Pro: 
  * only one release tracker per API Repository and meta-release, so only one entry on the meta-release page
* Cons: 
  * original history of the meta-release gets lost and is overwritten
  * the pre-releases (if any) for a patch release can not be documented in some useful way
  * the title of the release tracker has to be updated to reflect the new version number (potentially breaking links to the page)

B) Add a new release tracker for each public release of an API Repository, including Patch releases

* Pro
  * Clear rule: one release tracker for every public release of an API Repository
  * Visibility within the meta-release page that there were two or more release of the same API Repository within the meta-release
  * A clear documentation of the pre-releases and releases
* Cons
  * Some more effort for the creation of a new release tracker for a patch release 
  * potential mix of templates ... within the same meta-release the original release tracker should be copied instead using the updated template
  * Potentially multiple lines within the meta-release page for one API repository

**Possible evolution**

Decide for one the approaches, update the documentation.

Potentially fix the already done patch releases done with the other approach. In case of a decision for option B) that can be done by copying the current release tracker version (reflecting the patch release) and reverting the original back to the version at the time of the meta-release.

**Alternative solution**

NA

**Additional context**

**Comment by tanjadegroot** [comment]
In the RM team meeting today it was agreed that the approach A will be taken: update the original release tracker in the meta-release.

for the cons mentioned above:

original history of the meta-release gets lost and is overwritten - 
-  the comments field can be used for additional information.

the pre-releases (if any) for a patch release can not be documented in some useful way
- this information is available in the changelog

the title of the release tracker has to be updated to reflect the new version number (potentially breaking links to the page)
- short links are to be used to avoid breaking links when renaming pages.

The RM guidelines for patch management will be updated according to the above.

This closes the issue as completed
