### ISSUE TITLE
API Versioning - Aggregation

### ISSUE THREAD

**Issue by chrishowell** [camaraproject/ReleaseManagement#14]
**Problem description**
Using Major Versions only in the API path is going to break ASPs when there's aggregation across CSP implementations (using different minor versions). i.e. minor versions are not forward compatible.

**Expected behavior**
An ASP should not have different fields or formats coming from the same endpoint depending on the CSP.

**Alternative solution**
Add the minor version in the API path, patch release should just include documentation changes which don't affect the usage of the API.

**Additional context**
Raised in https://github.com/camaraproject/QualityOnDemand/issues/179

**Comment by tanjadegroot** [comment]
Agreed to Chris's comment. 
The CAMARA specific 0.y usage in the URL should also solve this issue or v0.

Close as done
