### ISSUE TITLE
Readiness Checklist step 6 update proposal

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/ReleaseManagement#16]
With a reference to Issue camaraproject/WorkingGroups#139 (https://github.com/camaraproject/WorkingGroups/issues/139).

I suggest to discuss about step 6 of the Readiness Check List (https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-Readiness-Checklist.md)

The discussion is driven by the goal of not slowing dawn the possibility for an Operator to promote or sell an API in its marketplace. Step 6 requires two Operators to have implemented and tested an API. Because of this step, it can happen that a stable API can not be marked as v1.0.0 because a second Operator has not yet implemented it.

A **proposal** could be a modification of step 6 having j**ust one Operator as mandatory** and a **second Operator or a CAMARA member as recommended.**

We could also evaluate the possibility for an API to be promoted and published on a marketplace even if in **Beta version**. A Beta version is expected to have possible improvements with minor releases while a "full version" (e.g. v1.0.0) is expected to be more stable. 

The idea is to gather, in this discussion, the opinion from the group and to **present a possible solution to the Governance WG.** this because it is a marketing decision rather than a technical one.

**Comment by tanjadegroot** [comment]
Please see the new API checklist proposal in 
https://github.com/camaraproject/ReleaseManagement/issues/28 with
https://github.com/camaraproject/ReleaseManagement/pull/29.

Explanations on the checklist items are here: https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreadinesschecklist

This should cover the points raised in this discussion.
As a result this issue can be closed.

**Comment by tanjadegroot** [comment]
@FabrizioMoggio Hi Fabrizio, are you OK to close this Issue ? thanks for your confirmation.

**Comment by tanjadegroot** [comment]
The API release checklist is now here: https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API-Readiness-Checklist.md

Finalized as described above and closed per lazy consensus as discussed in Release Management call on June 18th 2024
