### ISSUE TITLE
Is there a need for association of API definition (yaml) to Commonalities, ICM or Meta Release version?

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/ReleaseManagement#27]
**Problem description**

Currently there is no association between the API version and the respective Commonalities artifact versions (e.g. DG, Common_data.yaml) it complies with.

To my knowledge, the only association will be at the meta-release packaging.  I just wanted to raise the question if there is such a need.

**Possible evolution**

A possible solution will be to have reference(s) from each API definition (OAS file) to the respective Commonalities/ICM release, or the CAMARA Meta release.

Possible solution may be to require the use of the respective version in the externalDocs schema description property. 

**Alternative solution**

**Additional context**

**Comment by tanjadegroot** [comment]
Some thoughts: 
**Point 1: include meta-release in API and Comm/ICM release numbering**
- in API release numbering (rx.y) we could use x to reflect the meta-release. 
- e.g. we could start API release numbering (rx.y) with x= 24f (f for fall), so the first alpha-release of an API version would be r24f.1.
- The next meta-release APIs would have x= 25s (s for spring), etc.

Then Comm/ICM could also include the meta-release in its release version, e.g. release with r**24f-**x.y.z.
- e.g. so commonalities would start its first alpha-release with r24f-0.4.0-alpha.1, its first release-candidate with r24f-0.4.0-rc.1 and its public-release with r24f-0.4.0

**Point 2: meta-release in OAS spec**
In addition, or alternatively, we may put the meta-release in the OAS spec, by using the [Specification Extensions](https://spec.openapis.org/oas/v3.0.3#specification-extensions) mechanism (which is allowed for the Info object, but may impact tooling:
- in the Info Object, add a field of type string called "x-camara-meta-release" (this point)
- example: x-camara-meta-release: fall24 or x-camara-meta-release: 24f.
                  
**Point 3: Comm/ICM release in OAS spec**
Alternative to point 2, putting the actual Comm/ICM release version in the OAS API spec, would need something like this:
- x-camara-meta-release: fall24_commonalities-r0.4.0_icm-r0.2.0 or 
- x-camara-meta-release: 24f_commonalities-r0.4.0_icm-r0.2.0

**Point 4: no meta-release name in API or Commonalities/ICM releases**
We can leave out the meta-release name completely and use:
- current API release numbering (proposed to start at 1 (was 0))
- current Commonalities/ICM release numbering based on their version numbering
- in addition / alternatively, in Info object, put x-camara-common: commonalities-r0.4.0_icm-r0.2.0

**Open questions**
a) Not sure how hard it is to maintain this additional Info object field in the OAS ? could a linting rule check format and version (would need some metadata) ?

b) does this not overlap with what is in the API release note which should include something like (per template ?)
- "Update to align with Commonalities r0.4.0"
- "Update to align with ICM r0.2.0"

My pref would go for point 4 as the ref to the Comm/ICM release should be there already and the rest is duplicate info. We could add the statements above to the template if not already there.
Doing Point 1 in addition would not be a big deal IMHO but decision should be really soon.

thoughts ?

**Comment by tanjadegroot** [comment]
The selected solution is to add in the API YAML in the Info Object a CAMARA specific extension:
x-camara-commonalities: 0.4.

The dependency on the version of ICM shall be managed in the Commonalities changelog.md (can be changed later if needed).

The Commonalities team will add this to the API Guidelines: see https://github.com/camaraproject/Commonalities/pull/214

@gmuratk is it OK to close this issue ?

**Comment by gmuratk** [comment]
I see the solution picked (option 2 above) added to the mentioned PR so yes, it can be closed.  Thank you!
