### ISSUE TITLE
User story missing on the confluence page?

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/ReleaseManagement#39]
**Problem description**
Probably user story is missing in the Readiness checklist per API version table on [Confluence](https://wiki.camaraproject.org/display/CAM/API+Release+Process#APIReleaseProcess-APIreadinesschecklist).

**Expected action**

**Additional context**

**Comment by tanjadegroot** [comment]
Fixed ! thanks Ludovic

**Comment by bigludo7** [comment]
Thanks Tanja
