### ISSUE TITLE
Define Release Management for CAMARA

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/ReleaseManagement#4]
- Release Cycle
- Coordination between Sub Projects
- Release Scope Management
- Alignment with Open Gateway (see documentation/MeetingMinutes/CAMARA Project - SteeringCommittee - 2023-07-13 - Open Gateway API Roadmap Presentation to CAMARA TSC.pdf)

**Comment by tanjadegroot** [comment]
Closed per decision in RM call on June 18 2024 following availability of the [Release Management process](https://wiki.camaraproject.org/x/QAEG) in Confluence wiki and the RM Github documentation.
