### ISSUE TITLE
Update links in README.md file 

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/ReleaseManagement#40]
**Problem description**
Missing and outdate links / information in the README.md file need to be fixed.

(edit/added) The link within API-Readiness-Checklist.md to the wiki is also pointing not to the correct page.

**Expected action**
Update README.md file and API-Readiness-Checklist.md

**Additional context**
N/A

**Comment by hdamker** [comment]
@tanjadegroot I've extended with another link which need to be corrected.
