### ISSUE TITLE
Clarification on release tag and version naming for Commonalities and ICM

### ISSUE THREAD

**Issue by rartych** [camaraproject/ReleaseManagement#41]
**Problem description**
We have guidelines in https://wiki.camaraproject.org/display/CAM/Meta-release+Process#MetareleaseProcess-Versionandreleasenumbering
Hovewer, for version number `x.y.z-rc.n` the natural abbreviation is  `vx.y.z-rc.n`, while the release tag is `rx.y.z-rc.n` , which can be misleading.

**Expected action**
Clarification on  tags to be used in public release of Commonalities and ICM.

**Additional context**
Currently  Commonalities  are released with [r0.4.0-rc.1](https://github.com/camaraproject/Commonalities/releases/tag/r0.4.0-rc.1) and ICM with [v0.2.0-rc.1](https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/v0.2.0-rc.1) which is not consistent.

**Comment by tanjadegroot** [comment]
Let's correct ICM to r* in the next release
