### ISSUE TITLE
Process to publish v1.0 of an API

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/ReleaseManagement#5]
Related to camaraproject/ReleaseManagement#4

Assuming an API has met the API Readiness Checklist and the design guidelines, and has been approved by the sub-project team, what is the process for publishing it as a v1.0 CAMARA API?

One suggestion:
1. A GitHub [release tag](https://docs.github.com/en/repositories/releasing-projects-on-github/about-
releases) of `candidate-release-1.0` is applied to the repository
2. The `candidate-release-1.0` is reviewed by the Technical Steering Committee for a certain period and either sent back with feedback, or approved. If approved, then a `release-1.0` tag is applied. If not approved, the release tag is removed until the fixes have been made (then back to step 1)

This could fit well with repositories having only one API
* But if the repository  contains multiple APIs, then the risk is that the other APIs in that repository are pre-release versions and not suitable for publication. In which case,  either individual APIs get placed in individual repositories, or the situation is explained in the release notes.

**Comment by tanjadegroot** [comment]
The API Release Process is described 
- in GitHub here: https://github.com/camaraproject/ReleaseManagement/pull/31
- in wiki (Confluence) here: https://wiki.camaraproject.org/x/AgAVAQ
The wiki includes a section: "Releasing an API step by step"
Please review the PR #31 

Please inform if this request can be closed.

**Comment by tanjadegroot** [comment]
@Kevsy Hi Kevin, are you OK to close this Issue ? thanks for your confirmation.

**Comment by tanjadegroot** [comment]
Finalized as described above and closed per lazy consensus as discussion in Release Management call on June 18th 2024
