### ISSUE TITLE
Cross references into Commonalities, ICM and into the own API repository have to use links to a release, not into main

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#51]
**Problem description**

If API documentation is doing a cross reference into Commonalities or Identity and Consent Management (ICM) they must use a link which is pointing to the released version.

Specifically:

Currently the APIs are copying the (mandatory) text from [CAMARA-API-access-and-user-consent.md#mandatory-template-for-infodescription-in-camara-api-specs](https://github.com/camaraproject/IdentityAndConsentManagement/blob/v0.2.0-rc.1/documentation/CAMARA-API-access-and-user-consent.md#mandatory-template-for-infodescription-in-camara-api-specs) which contains a link into the main branch of ICM: https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-Security-Interoperability.md. 

But the link should go to the released version of the document in ICM.
Additional challenge: ICM has currently only a release candidate tag (`v0.2.0-rc.1`). The public release will done most probably only mid of August and will have the tag `r0.2.0` 

**Possible evolution**

First of all it has to be clarified if the cross-reference links should go to a concrete release of Commonalities & ICM repositories (which would miss e.g. patch releases done afterwards within for the same Meta-Release) or rather to some permanent URL/Tag with belongs to a respective Meta-Release and will be updated when needed.

Proposal is to maintain an additional tag within Commonalities and ICM which point to the pre-release or latest release for the current meta-release. 

A long-term solution to maintain correct links (and other dependencies, e.g. on the own release tag, and references to CAMARA_common) might need to include scripting, variables and a configuration file which will generate the target files based on on source files with variables within the API repositories.

**Alternative solutions**

As a long-term solution can't be established for the current release cycle, two potential ways forward:

A) Correcting the cross links manually:

* Commonalities and ICM
  * Are setting additional tags on their current release candidates, e.g. 'fall24' or 'r1'
    * the advantage of such additional tag: it is already available with release candidates and stays valid if there are patch release after the meta-release (e.g. Commonalities 0.4.1)
  * are fixing their internal cross reference links to use this tag
  * are moving the 'fall24' or 'r1' tag when creating new (pre-)releases for the Meta-Release
 
* Within API Sub Projects all links will be corrected
   * for cross reference to Commonalities and ICM replacing 'main' with 'fall24'
   * for links into own repository using the concrete release tag
   * if possible already within the current release PRs or
   * if necessary as a bug fix between first release candidate and public release

B) Accept the cross reference into Commonalities and ICM main branch for this release, but considering the existence of these links in the work of ICM 

**Additional context**

_Original posted by @sfnuser in https://github.com/camaraproject/NumberVerification/pull/121#discussion_r1690204839_

> As we are cross referencing commonalities version here, shouldn't we refer to the `release snapshot` of ICM documents instead of referring to the main branch (i.e.) in line 43 the line [CAMARA-API-access-and-user-consent.md](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md) should point to the release candidate of ICM and not `main` - the running version.
> 
> This is applicable to the UML image link too in line 33 because if CAMARA repo structure changes, the released spec is affected.
> 
> This comment is applicable to all CAMARA release candidate APIs I suppose.

**Comment by hdamker** [comment]
@camaraproject/release-management_maintainers please have a view on this issue and add your view on:

* Should we introduce an additional tag which is indicating the current pre- or latest public release for a Meta-Release (to be updated from the release candidate up to last patch release within the context of a Meta-Release)?
* if yes, would be an appropriate name? 'Fall24', 'r1' or something else
* Should we take the effort to correct as many links as possible within the current release cycle (alternative option A) vs B))?

**Comment by tanjadegroot** [comment]
I think option B is fine for this first meta-release. 

Maybe option C would be to 

- look at removing links in the API specs (at least for documentation), as we have the x-commonalities extension indicating the version.
- for the common_data types, maybe tooling could be applied to resolve external references before release (meaning to include the common data types so that the API definition file is autonomous. Also because not all OAS tools support external referencing. 

the issue remains for ICM / Comm patches that impact APIs - open question is is we need to re-release all the meta-release APIs as well ?

**Comment by soadeyemo** [comment]
@hdamker @camaraproject/release-management_maintainers
Yes I believe this is needed. And I vote for name - Fall24.
Also think option B will suffice for now.

**Comment by hdamker** [comment]
For Fall24 the topic was solved by avoiding deep links into other repositories. 

If there is a need for deep links in later release cycles a new issue should be opened.
