### ISSUE TITLE
CallForwardingSignal r1.1 release review

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/ReleaseManagement#52]
**Release PR or issue to review**

- ~~https://github.com/camaraproject/CallForwardingSignal/pull/75~~
- ~~https://github.com/camaraproject/CallForwardingSignal/pull/68~~
- https://github.com/camaraproject/CallForwardingSignal/pull/91

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by tanjadegroot** [comment]
Main review comments:
- YAML: missing x-camara-commonalities
- wrong version in test files
- Herbert: r1.1 was released without RM review. Create a r1.2  with RM comments.
- rename API readiness checklist file with full API name in front.

Beyond RM aspects, some suggestions:
- User Stories: terminology rather Telco focused (Customer --> End-user, Operator Platform --> API Provider)
- rename API to call-forwarding-status (iso call-forwarding-signal)

**Comment by hdamker** [comment]
* create issue https://github.com/camaraproject/CallForwardingSignal/issues/90 which should be addressed before r1.2
* created a release PR https://github.com/camaraproject/CallForwardingSignal/pull/91 for the final changes

**Comment by hdamker** [comment]
Release r1.2 created and tracker updated.

**Comment by hdamker** [comment]
Plan for the M4 release: https://github.com/camaraproject/CallForwardingSignal/discussions/92
