### ISSUE TITLE
WebRTC r1.1 release review

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/ReleaseManagement#53]
**Release PR or issue to review**

https://github.com/camaraproject/WebRTC/pull/47

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [ ] API Definition files (YAML) (check version in info & servers objects)  
- [ ] test file(s) availability
- [ ] changelog updated
- [ ] readme updated (enforce correct release number / API version naming) 
- [ ] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [ ] API release tracker available on wiki
- [ ] Review comments addressed (by Sub Project)
- [ ] Release PR approved (on behalf of Release Management)
- [ ] PR merged (by Sub Project codeowner)
- [ ] Release created within GitHub (by Sub Project codeowner)
- [ ] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by hdamker** [comment]
No release tracking page(s) yet.

**Comment by soadeyemo** [comment]
few comments in https://github.com/camaraproject/WebRTC/pull/47
