### ISSUE TITLE
HomeDevicesQoD r1.1 release review

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/ReleaseManagement#54]
**Release PR or issue to review**

https://github.com/camaraproject/HomeDevicesQoD/pull/68

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API Definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by tanjadegroot** [comment]
Main review comments: 
- update API definition to remove termsOfService and contact fields
- missing in-line documentation - to be complete by M4

**Comment by jpengar** [comment]
> Main review comments:
> 
> * update API definition to remove termsOfService and contact fields
> * missing in-line documentation - to be complete by M4

@tanjadegroot Before I merge https://github.com/camaraproject/HomeDevicesQoD/pull/68 (which is already approved), please take a look at my comment https://github.com/camaraproject/HomeDevicesQoD/pull/68#issuecomment-2259912103. I don't think in-line documentation is missing, errors are documented as part of the endpoint definition in the API spec (as done many other subprojects), and as discussed in the last Release Management WG call, the documentation template looks a bit outdated in that sense.

**Comment by hdamker** [comment]
Release successfully created - congratulation 🎉
