### ISSUE TITLE
SimSwap r1.1 release review

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/ReleaseManagement#55]
**Release PR or issue to review**

https://github.com/camaraproject/SimSwap/pull/127

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue. 

- [x] API Definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by hdamker** [comment]
https://github.com/camaraproject/SimSwap/pull/129 (for sim-swap-subscriptions v0.1.0-alpha.1) reviewed as requested by @bigludo7 -> minor comments added.

**Comment by hdamker** [comment]
Main review results (based on main branch and draft PR https://github.com/camaraproject/SimSwap/pull/127
* sim-swap.yaml: Authorization and Authentication section in info.description must be updated (opened issue for that)
* Mandatory test files for sim-swap still in PR (correctly mentioned within the API Readiness Checklist)
* API Readiness Checklists, CHANGELOG and README.md: only minor comments

**Comment by hdamker** [comment]
Release created and release tracker updated

**Comment by AxelNennker** [comment]
I found a typo in the simswap yaml file
https://github.com/camaraproject/SimSwap/pull/137
