### ISSUE TITLE
Updates of review issue template with more functionality

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/ReleaseManagement#61]
**Problem description**

Extending the review issue template with informatiuon on release mgmt action beyond the API review

**Possible evolution**

Rename to "Review actions"

Add a section Release actions with the following as tickboxes

API Release Tracker available
Review comments addressed (by Sub Project)
Release PR approved (on behalf of Release Management)
PR merged (by Sub Project codeowner)
Release created within GitHub (by Sub Project codeowner)
Release Tracker updated (M3 date = creation date of release?)

**Comment by tanjadegroot** [comment]
@hdamker  please check is it meets your proposal and merge. 
We will manally need to extend to existing review issues by copying from the updated template

**Comment by hdamker** [comment]
> @hdamker please check if it meets your proposal and merge. We will need to manually extend to existing review issues by copying from the updated template
Looks good for me, comments in the PR. The update is not difficult, just replace the yet untouched part of the issue description.

> I will actually do a manual copy into the first to review issues (botttom up) and start to use it. This may leead to some additional points to add in the PR

Testing is good, I currently doing it with DeviceStatus in #57

**Comment by tanjadegroot** [comment]
There is no real easy way to check the Commonalities / ICM alignment (beyond version and Auth section in info.description. Some teams have put the linter output snapshot in the issue

should we ask both teams to add a short main check points list on the confluence page ? https://wiki.camaraproject.org/display/CAM/Guidance+for+release+review

**Comment by hdamker** [comment]
> There is no real easy way to check the Commonalities / ICM alignment (beyond version and Auth section in info.description. Some teams have put the linter output snapshot in the issue
> 
> should we ask both teams to add a short main check points list on the confluence page ? https://wiki.camaraproject.org/display/CAM/Guidance+for+release+review

Yes, a checklist makes sense to me. About doing the actual check: maybe the experts from Commonalities and ICM are best suited to do these checks. Maybe not blocking the creation of the release candidates, but based on the actual release candidates.
