### ISSUE TITLE
CarrierBillingCheckOut r1.1 release review

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#70]
**Release PR or issue to review**

https://github.com/camaraproject/CarrierBillingCheckOut/pull/167

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by hdamker** [comment]
See comment https://github.com/camaraproject/CarrierBillingCheckOut/pull/167#issuecomment-2261111782 ... PR looks quite good and has approvals from Sub Project, but RM not yet added as reviewer.

**Comment by rartych** [comment]
info & servers objects corrected in [Release PR](https://github.com/camaraproject/CarrierBillingCheckOut/pull/167) 
final changelog & readme updates also in [Release PR](https://github.com/camaraproject/CarrierBillingCheckOut/pull/167)

**Comment by hdamker** [comment]
On behalf of sub project:
* merged release PR (already on August 9th)
* corrected minor link error in CHANGELOG.md
* created the release tag
* updated the two release tracker pages
