### ISSUE TITLE
CallForwardingSignal r1.3 release review (M4)

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#77]
**Release PR or issue to review**

~~https://github.com/camaraproject/CallForwardingSignal/pull/95~~
https://github.com/camaraproject/CallForwardingSignal/pull/101
**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by hdamker** [comment]
Initial review comments left: CHANGELOG.md need to be for full new API, API Readiness Checklist and .feature files need to updated as well.

**Comment by FabrizioMoggio** [comment]
I should have addressed all the issues with an update on the current PR: https://github.com/camaraproject/CallForwardingSignal/pull/95

issues: 
https://github.com/camaraproject/CallForwardingSignal/issues/96
https://github.com/camaraproject/CallForwardingSignal/issues/97
https://github.com/camaraproject/CallForwardingSignal/issues/98

**Comment by tanjadegroot** [comment]
M4 review:

changelog.md: need to update links with renamed API yaml file.
readme.md: same update needed as above
few editorial comments

release tracker to be updated to 0.2.0 (from 0.2.0-rc.2)

with these updates done, release r1.3 can be created: LGTM form release mgmt.

**Comment by FabrizioMoggio** [comment]
@tanjadegroot 

comment addressed with: https://github.com/camaraproject/CallForwardingSignal/pull/101

About the release tracker:
https://wiki.camaraproject.org/display/CAM/call-forwarding-signal+v0.2.0

it already refers to rel v0.2.0 (maybe I did it too early :-) )

**Comment by FabrizioMoggio** [comment]
Public Release tag created (https://github.com/camaraproject/CallForwardingSignal/releases/tag/r1.3) and release tracker updated.

**Comment by hdamker** [comment]
> Public Release tag created (https://github.com/camaraproject/CallForwardingSignal/releases/tag/r1.3) and release tracker updated.

@FabrizioMoggio you are quite fast, @tanjadegroot had not even a chance to approve the release PR 😉

**Comment by tanjadegroot** [comment]
Hereby explicit RM approval of the PR (after the fact).
All OK and this issue can be closed.
