### ISSUE TITLE
SimpleEdgeDiscovery r1.3 release review (M4 for stable version)

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#82]
**Release PR or issue to review**

https://github.com/camaraproject/SimpleEdgeDiscovery/pull/41

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Review by Commonalities and ICM**

- [x] Check if results from https://github.com/camaraproject/Commonalities/issues/266 are addressed
- [x] Check if results from https://github.com/camaraproject/IdentityAndConsentManagement/issues/189 are addressed

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by tanjadegroot** [comment]
LGTM provided from RM

**Comment by Kevsy** [comment]
Just merged the M4 PR following CODEOWNER approval 👍

**Comment by Kevsy** [comment]
Final two tasks done:

Release created within GitHub (by Sub Project codeowner)
Release Tracker updated (with creation date of the release and the release tag link)

**Comment by rartych** [comment]
Closing as all tasks completed.
