### ISSUE TITLE
Clarify how to proceed with requirement "Test result statement" for stable APIs

### ISSUE THREAD

**Issue by jlurien** [camaraproject/ReleaseManagement#89]
**Problem description**

API-Readiness-Checklist indicates that for stable APIs a mandatory check is 

Nr | API release assets | Explanation
-- | -- | --
9 | Test result statement | A statement in a discussion issue of the API Sub Project by at least one of the API Sub Project members that the Gherkin feature files have been successfully executed against their (lab) API implementation.

Which would imply passing the enhanced test plan to the last RC after M3 in a lab environment, but this is not really feasible for this meta-release, due to the reduced period between M3 and M4, and the delay in the availability of enhanced test plans.

**Possible evolution**

Discuss at release and project management level how to deal with the exceptionality for this first meta-release, and give guidelines to APIs intending to release stable versions about how to proceed and fill the API-Readiness-Checklist

**Comment by jlurien** [comment]
Thanks @tanjadegroot, what about the Status column? Should APIs fill it with "N"?

**Comment by hdamker** [comment]
> Thanks @tanjadegroot, what about the Status column? Should APIs fill it with "N"?

My take would fill it with "N", allows later in a patch release to change it to "Y" (if bugs had to be fixed).

**Comment by tanjadegroot** [comment]
> Thanks @tanjadegroot, what about the Status column? Should APIs fill it with "N"?

yes, let me update the description accordingly

**Comment by tanjadegroot** [comment]
Implemented and closed as completed
