### ISSUE TITLE
Consolidation Issue for open points release management

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/ReleaseManagement#9]
**Problem description**
Currently, there are several open issues (7 in total) which touch the topic of release management, and some are even duplicates.

**Expected action**
This issue will provide a consolidated view of all open issues for release management under commonalities.  This will help the TSC to address the topic in a more structured way. 

Under this issue, contributors are also requested to nominate themselves if they would like to participate in the release management concept work that will be undertaken in the TSC. Would be very useful if you could also specify if you wish to be an active contributor or just a reviewer, or both (depending on your interests and the time you can spend on the topic).  

**Additional context**
Current open issues and categories:

1.  API Versioning (Alpha/Beta vs Semantic...)
      https://github.com/camaraproject/ReleaseManagement/issues/13
      https://github.com/camaraproject/ReleaseManagement/issues/14

2.   API Family versioning
       https://github.com/camaraproject/ReleaseManagement/issues/12
  
3.  Release Branches
     https://github.com/camaraproject/ReleaseManagement/issues/10

4.  API Release 1.0 and general conformance
    https://github.com/camaraproject/ReleaseManagement/issues/16
    https://github.com/camaraproject/Governance/issues/141
    https://github.com/camaraproject/Commonalities/issues/201
    https://github.com/camaraproject/Commonalities/issues/200

5. Camara-wide release
    Though there are no open issues on this topic, it has been discussed on several occasions in commonalities.

**Comment by tanjadegroot** [comment]
Final status of this issue:

API Versioning (Alpha/Beta vs Semantic...)
https://github.com/camaraproject/ReleaseManagement/issues/13 - Closed
https://github.com/camaraproject/ReleaseManagement/issues/14 - Marked as backlog

API Family versioning
https://github.com/camaraproject/ReleaseManagement/issues/12 - Closed

Release Branches
https://github.com/camaraproject/ReleaseManagement/issues/10 - Closed

API Release 1.0 and general conformance
https://github.com/camaraproject/ReleaseManagement/issues/16 - Closed
https://github.com/camaraproject/Governance/issues/141 - Transferred to Governance for discussion
https://github.com/camaraproject/Commonalities/issues/201 - Transferred back to Commonalities with info and closed there.
https://github.com/camaraproject/Commonalities/issues/200 - Transferred back to Commonalities and closed there.

Camara-wide release
Though there are no open issues on this topic, it has been discussed on several occasions in commonalities. - Closed - Meta-release process defined (see issue #4)
