### ISSUE TITLE
DeviceLocation r1.2 release review (M4 with stable API version)

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#90]
**Release PR or issue to review**

https://github.com/camaraproject/DeviceLocation/pull/252

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

**Comment by tanjadegroot** [comment]
Samuel provided the LGTM from Release Mgmt
I found a small bug in the feature files and added some comments on text - up to the team to decide when to fix.

Main points raised in the review:
- the mandatory Device object should be optional and that the explanation about using the device in teh access token should be added.
- the device should be included in the geolocation API as an optional parameter - left for next release (https://github.com/camaraproject/DeviceLocation/pull/252#issuecomment-2340236900)

**Comment by jlurien** [comment]
Latest comments by @tanjadegroot addressed in the PR, and it is explained why device was kept as required in the subscriptions (aligned with DeviceStatus). Discussion around this will be open for a next release, across all affected APIs. PR is now merged, r1.2 created and release tracker updated.

**Comment by tanjadegroot** [comment]
All done. This issue can be closed
