### ISSUE TITLE
KnowYourCustomer r1.3 release review (Patch release with kyc-match v0.2.1, revoking r1.2)

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#95]
**Release PR or issue to review**

https://github.com/camaraproject/KnowYourCustomer/pull/149

**Review actions**

Assign this issue to yourself and follow the below list.
For any review action, review the file(s) in the issue/PR listed above. 
Put comments in the above issue or PR if they concern non-changed files/text.
Put a short summary of the main review result here into the review issue.

- [x] API definition files (YAML) (check version in info & servers objects)  
- [x] test file(s) availability
- [x] changelog updated
- [x] readme updated (enforce correct release number / API version naming) 
- [x] API readiness checklist(s)

**Release actions**

Assign this issue to yourself or another RM team member and follow the below list. 
When done, tick the box in this issue. 

- [x] API release tracker available on wiki
- [x] Review comments addressed (by Sub Project)
- [x] Release PR approved (on behalf of Release Management)
- [x] PR merged (by Sub Project codeowner)
- [x] Release created within GitHub (by Sub Project codeowner)
- [x] Release Tracker updated (with creation date of the release and the release tag link)

**Additional comments**

For r1.2 the CHANGELOG.md contains the sentence:

> **NOTE: Release r1.2 has been revoked due to a bug found in kyc-match v0.2.0 code. It is fixed in kyc-match v0.2.1 as part of r1.3 release.**

It is planned to delete the release r1.2 from the repository.

**Comment by fernandopradocabrillo** [comment]
Hi @hdamker, we ahve already created the release. So the rest of the checks can be completed.
Thanks!

**Comment by hdamker** [comment]
@fernandopradocabrillo thanks - great teamwork!
